manipulate rules

In [13]:
import pandas as pd
import numpy as np

data=pd.read_csv('rules_df.csv')

Rules:
    1. start with the highest ranked pair, assign each of these IPs to server '0'
    2. go to next highest pair, check if IP_B exists in any other server, 
        If it does not, then this pair (IP_A and IP_B) can be assigned to the first server that has room. 
        IF IP_B has already been assigned, find the server it has been assigned to and assign IP_A to that server.

In [14]:
num_A=data['IP_A'].nunique()

In [15]:
num_B=data['IP_B'].nunique()

In [16]:
b=(data['IP_B']).unique()

In [17]:
a=(data['IP_A']).unique()

In [18]:
#Total unique IPs 
num_A+num_B

351

In [19]:
(329+22)/20

17.55

We should have 18 servers to hold all of these unique IP addreses.

In [20]:
for i in a:
    if i in b:
        print(i)
#every IP is a id unique and does not exist in b

In [21]:
type(b)

numpy.ndarray

In [22]:
#create a list of all unique IPs
un_ips=np.append(a,b)

In [23]:
data

,Unnamed: 0,IP_A,IP_B,confidence,pairs,pairs2,frequency,avg_norm_latency,total_duration,total_packets,norm_latency,latency_rank,pair_ID,server_A,server_B,server
0,326,13053_118,192.168.210.56,1.000000,"['13053_118', '192.168.210.56']","('13053_118', '192.168.210.56')",12439,0.255143,15736.067,44427,8.609759e-03,107.096797,0,0.0,0.0,0
1,299,13049_193,192.168.210.56,1.000000,"['13049_193', '192.168.210.56']","('13049_193', '192.168.210.56')",1775,0.372031,79345.558,245786,4.341276e-02,77.057656,1,NaN,NaN,0
2,317,13053_106,192.168.210.56,1.000000,"['13053_106', '192.168.210.56']","('13053_106', '192.168.210.56')",7180,0.343261,14717.209,31305,8.052306e-03,57.815558,2,NaN,NaN,0
3,322,10272_44,192.168.220.51,1.000000,"['10272_44', '192.168.220.51']","('10272_44', '192.168.220.51')",10094,0.091117,3665.353,26275,2.005444e-03,20.242956,3,NaN,NaN,0
4,319,14170_51,192.168.220.51,1.000000,"['14170_51', '192.168.220.51']","('14170_51', '192.168.220.51')",8094,0.022052,1881.134,26460,1.029235e-03,8.330628,4,NaN,NaN,0
5,327,192.168.100.14,192.168.220.51,0.768957,"['192.168.100.14', '192.168.220.51']","('192.168.100.14', '192.168.220.51')",9938,0.023863,1344.801,11257,7.357882e-04,7.312264,5,NaN,NaN,0
6,321,192.168.100.2,192.168.220.51,0.988571,"['192.168.100.2', '192.168.220.51']","('192.168.100.2', '192.168.220.51')",9947,0.023174,1286.182,11226,7.037157e-04,6.999860,6,NaN,NaN,0
7,320,192.168.100.1,192.168.220.51,1.000000,"['192.168.100.1', '192.168.220.51']","('192.168.100.1', '192.168.220.51')",9770,0.022819,1246.609,11053,6.820639e-04,6.663764,7,NaN,NaN,0
8,325,12087_137,192.168.220.47,1.000000,"['12087_137', '192.168.220.47']","('12087_137', '192.168.220.47')",12158,0.010903,547.857,47097,2.997520e-04,3.644384,8,NaN,NaN,0
9,310,11685_203,192.168.210.53,0.976927,"['11685_203', '192.168.210.53']","('11685_203', '192.168.210.53')",3472,0.006333,1560.202,978322,8.536418e-04,2.963844,9,NaN,NaN,0
10,307,11714_20,192.168.210.53,0.965680,"['11714_20', '192.168.210.53']","('11714_20', '192.168.210.53')",2870,0.006435,1285.935,802694,7.035806e-04,2.019276,10,NaN,NaN,1
11,318,14185_238,192.168.220.51,1.000000,"['14185_238', '192.168.220.51']","('14185_238', '192.168.220.51')",8084,0.022407,417.154,9549,2.282397e-04,1.845090,11,NaN,NaN,1
12,314,11681_180,192.168.210.54,0.996400,"['11681_180', '192.168.210.54']","('11681_180', '192.168.210.54')",4705,0.022177,685.636,31111,3.751357e-04,1.765014,12,NaN,NaN,1
13,328,192.168.220.1,192.168.220.51,0.986176,"['192.168.220.1', '192.168.220.51']","('192.168.220.1', '192.168.220.51')",13198,0.001058,114.218,13385,6.249271e-05,0.824779,13,NaN,NaN,1
14,306,10692_1,192.168.220.43,0.840541,"['10692_1', '192.168.220.43']","('10692_1', '192.168.220.43')",2488,0.051287,484.838,10333,2.652720e-04,0.659997,14,NaN,NaN,1
15,316,14172_51,192.168.220.51,1.000000,"['14172_51', '192.168.220.51']","('14172_51', '192.168.220.51')",6600,0.004654,135.466,11514,7.411824e-05,0.489180,15,NaN,NaN,1
16,308,10763_18,192.168.220.51,0.925314,"['10763_18', '192.168.220.51']","('10763_18', '192.168.220.51')",2800,0.013844,265.974,6528,1.455238e-04,0.407467,16,NaN,NaN,1
17,180,13379_49,192.168.220.48,1.000000,"['13379_49', '192.168.220.48']","('13379_49', '192.168.220.48')",251,0.041999,2361.056,76754,1.291817e-03,0.324246,17,NaN,NaN,1
18,301,14184_244,192.168.220.51,0.977351,"['14184_244', '192.168.220.51']","('14184_244', '192.168.220.51')",1985,0.036709,280.603,3394,1.535278e-04,0.304753,18,NaN,NaN,1
19,312,10597_84,192.168.220.51,0.847014,"['10597_84', '192.168.220.51']","('10597_84', '192.168.220.51')",3333,0.013994,141.249,5280,7.728233e-05,0.257582,19,NaN,NaN,1
20,284,13184_115,192.168.210.49,1.000000,"['13184_115', '192.168.210.49']","('13184_115', '192.168.210.49')",843,0.100864,460.066,3286,2.517184e-04,0.212199,20,NaN,NaN,2
21,303,10123_41,192.168.220.51,0.938568,"['10123_41', '192.168.220.51']","('10123_41', '192.168.220.51')",2032,0.017302,185.681,7440,1.015926e-04,0.206436,21,NaN,NaN,2
22,287,12486_238,192.168.210.52,1.000000,"['12486_238', '192.168.210.52']","('12486_238', '192.168.210.52')",959,0.011183,312.523,5633,1.709924e-04,0.163982,22,NaN,NaN,2
23,302,10123_71,192.168.220.51,0.943953,"['10123_71', '192.168.220.51']","('10123_71', '192.168.220.51')",1920,0.015775,152.122,6618,8.323133e-05,0.159804,23,NaN,NaN,2
24,305,10597_79,192.168.220.51,0.800463,"['10597_79', '192.168.220.51']","('10597_79', '192.168.220.51')",2074,0.018203,113.829,3521,6.227988e-05,0.129168,24,NaN,NaN,2
25,311,13047_59,192.168.210.56,0.982118,"['13047_59', '192.168.210.56']","('13047_59', '192.168.210.56')",3570,0.005158,57.833,6448,3.164248e-05,0.112964,25,NaN,NaN,2
26,283,11752_128,192.168.220.47,0.954491,"['11752_128', '192.168.220.47']","('11752_128', '192.168.220.47')",797,0.012284,245.109,17397,1.341078e-04,0.106884,26,NaN,NaN,2
27,280,10154_212,192.168.220.51,0.976501,"['10154_212', '192.168.220.51']","('10154_212', '192.168.220.51')",748,0.042254,235.750,2419,1.289872e-04,0.096482,27,NaN,NaN,2
28,300,13035_162,192.168.220.51,0.989491,"['13035_162', '192.168.220.51']","('13035_162', '192.168.220.51')",1789,0.016915,79.814,2660,4.366907e-05,0.078124,28,NaN,NaN,2
29,304,10123_37,192.168.220.51,0.967444,"['10123_37', '192.168.220.51']","('10123_37', '192.168.220.51')",2199,0.004536,63.193,3668,3.457513e-05,0.076031,29,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,12,10057_27,192.168.220.43,1.000000,"['10057_27', '192.168.220.43']","('10057_27', '192.168.220.43')",133,0.005008,9.765,433,5.342777e-06,0.000711,299,NaN,NaN,29
300,75,11701_221,192.168.220.51,0.767857,"['11701_221', '192.168.220.51']","('11701_221', '192.168.220.51')",129,0.016699,9.881,311,5.406245e-06,0.000697,300,NaN,NaN,30
301,172,10981_41,192.168.220.51,0.737705,"['10981_41', '192.168.220.51']","('10981_41', '192.168.220.51')",180,0.005867,6.726,625,3.680033e-06,0.000662,301,NaN,NaN,30
302,90,12571_92,192.168.220.47,0.764045,"['12571_92', '192.168.220.47']","('12571_92', '192.168.220.47')",136,0.013198,8.769,279,4.797830e-06,0.000653,302,NaN,NaN,30
303,97,12803_143,192.168.220.51,0.900552,"['12803_143', '192.168.220.51']","('12803_143', '192.168.220.51')",163,0.010421,7.167,297,3.921319e-06,0.000639,303,NaN,NaN,30
304,40,13600_4,192.168.220.51,0.872483,"['13600_4', '192.168.220.51']","('13600_4', '192.168.220.51')",130,0.014537,8.775,313,4.801113e-06,0.000624,304,NaN,NaN,30
305,84,11698_111,192.168.220.45,0.861272,"['11698_111', '192.168.220.45']","('11698_111', '192.168.220.45')",149,0.010004,7.535,375,4.122665e-06,0.000614,305,NaN,NaN,30
306,160,10088_36,192.168.220.47,0.832599,"['10088_36', '192.168.220.47']","('10088_36', '192.168.220.47')",189,0.012716,5.882,678,3.218250e-06,0.000608,306,NaN,NaN,30
307,6,10708_220,192.168.220.43,1.000000,"['10708_220', '192.168.220.43']","('10708_220', '192.168.220.43')",128,0.014459,8.668,265,4.742570e-06,0.000607,307,NaN,NaN,30
308,5,14155_88,192.168.210.54,1.000000,"['14155_88', '192.168.210.54']","('14155_88', '192.168.210.54')",128,0.002086,8.207,962,4.490340e-06,0.000575,308,NaN,NaN,30
309,85,10320_211,192.168.220.51,0.758621,"['10320_211', '192.168.220.51']","('10320_211', '192.168.220.51')",132,0.026887,7.848,188,4.293919e-06,0.000567,309,NaN,NaN,30
310,138,10698_157,192.168.210.55,0.980583,"['10698_157', '192.168.210.55']","('10698_157', '192.168.210.55')",202,0.002882,4.986,664,2.728017e-06,0.000551,310,NaN,NaN,31
311,20,10510_126,192.168.220.51,1.000000,"['10510_126', '192.168.220.51']","('10510_126', '192.168.220.51')",137,0.013315,7.117,312,3.893963e-06,0.000533,311,NaN,NaN,31
312,4,14154_89,192.168.210.54,1.000000,"['14154_89', '192.168.210.54']","('14154_89', '192.168.210.54')",128,0.007364,7.290,244,3.988617e-06,0.000511,312,NaN,NaN,31
313,154,10045_94,192.168.210.54,0.705882,"['10045_94', '192.168.210.54']","('10045_94', '192.168.210.54')",156,0.004378,5.660,263,3.096786e-06,0.000483,313,NaN,NaN,31
314,100,10013_240,192.168.220.47,0.801105,"['10013_240', '192.168.220.47']","('10013_240', '192.168.220.47')",145,0.004180,5.898,609,3.227005e-06,0.000468,314,NaN,NaN,31
315,324,192.168.220.2,192.168.220.51,0.966079,"['192.168.220.2', '192.168.220.51']","('192.168.220.2', '192.168.220.51')",10680,0.000003,0.067,10688,3.665807e-08,0.000392,315,NaN,NaN,31
316,19,10088_247,192.168.220.46,1.000000,"['10088_247', '192.168.220.46']","('10088_247', '192.168.220.46')",136,0.007592,4.264,318,2.332985e-06,0.000317,316,NaN,NaN,31
317,10,12468_200,192.168.220.50,1.000000,"['12468_200', '192.168.220.50']","('12468_200', '192.168.220.50')",132,0.002812,3.736,373,2.044098e-06,0.000270,317,NaN,NaN,31
318,25,10016_144,192.168.220.51,1.000000,"['10016_144', '192.168.220.51']","('10016_144', '192.168.220.51')",139,0.006999,3.458,465,1.891994e-06,0.000263,318,NaN,NaN,31
319,166,10001_210,192.168.220.51,0.810345,"['10001_210', '192.168.220.51']","('10001_210', '192.168.220.51')",188,0.003574,2.271,323,1.242545e-06,0.000234,319,NaN,NaN,31
320,26,12469_84,192.168.220.47,1.000000,"['12469_84', '192.168.220.47']","('12469_84', '192.168.220.47')",140,0.001228,2.520,536,1.378781e-06,0.000193,320,NaN,NaN,32
321,16,10085_11,192.168.220.51,1.000000,"['10085_11', '192.168.220.51']","('10085_11', '192.168.220.51')",134,0.001406,2.585,412,1.414345e-06,0.000190,321,NaN,NaN,32
322,51,10003_90,192.168.220.47,1.000000,"['10003_90', '192.168.220.47']","('10003_90', '192.168.220.47')",156,0.000634,1.888,626,1.032992e-06,0.000161,322,NaN,NaN,32
323,141,11585_52,192.168.220.45,0.790476,"['11585_52', '192.168.220.45']","('11585_52', '192.168.220.45')",166,0.001838,1.686,467,9.224703e-07,0.000153,323,NaN,NaN,32
324,2,10759_43,192.168.220.47,1.000000,"['10759_43', '192.168.220.47']","('10759_43', '192.168.220.47')",128,0.004098,1.416,414,7.747437e-07,0.000099,324,NaN,NaN,32
325,41,10297_248,192.168.220.51,0.933333,"['10297_248', '192.168.220.51']","('10297_248', '192.168.220.51')",140,0.001828,0.767,384,4.196529e-07,0.000059,325,NaN,NaN,32
326,315,192.168.200.2,192.168.220.51,1.000000,"['192.168.200.2', '192.168.220.51']","('192.168.200.2', '192.168.220.51')",5231,0.000000,0.000,5231,0.000000e+00,0.000000,326,NaN,NaN,32
327,323,192.168.210.1,192.168.220.51,0.969532,"['192.168.210.1', '192.168.220.51']","('192.168.210.1', '192.168.220.51')",10692,0.000000,0.000,10692,0.000000e+00,0.000000,327,NaN,NaN,32
328,194,13831_172,192.168.220.48,1.000000,"['13831_172', '192.168.220.48']","('13831_172', '192.168.220.48')",268,0.000000,0.000,268,0.000000e+00,0.000000,328,NaN,NaN,32

In [24]:
data50=data[0:50]

In [58]:
#server 0 is a bucket, want to count how many go into bucket
serversize=20
serverlist=[]
server={}
ips={}
#serverlist.append(server) #put a new server dictionary into our list

serverid=0
for i in range(0,len(data)):
    if len(server)==serversize:
        serverlist.append(server)
        server={}
        serverid=serverid+1
    #if IP_B is in this server, it is a duplicate, so we only want to add in the IP_A which has not been added to the server yet
    if (data['IP_B'][i] in server) and (len(server)<=(serversize-1)) and (data['IP_A'][i] not in ips):
        server[data['IP_A'][i]]=serverid
        ips[data['IP_A'][i]]=1
    #if IP_B is not in the server, and the server has room for 2 more, and it's matching IP_A is also not in the ip list we know IP_A hasn't been added yet.
    #Thus, we need to add both the IP_A and IP_B in this row to this server and the ip list.
    if (data['IP_B'][i] not in server) and len(server)<=(serversize-2) and (data['IP_A'][i] not in ips):
        server[data['IP_A'][i]]=serverid
        server[data['IP_B'][i]]=serverid
        ips[data['IP_A'][i]]=1
        ips[data['IP_B'][i]]=1                                                                                                                                                                                                                          
   ##if IP_B is not in the server, and the server has room for only 1 more, and it's matching IP_A is also not in the ip list we know IP_A hasn't been added yet.
    #we need to create a new server, and add both the IP_A and IP_B in this row to this new server and the ip list.
    if (data['IP_B'][i] not in server) and len(server)==(serversize-1) and (data['IP_A'][i] not in ips): #if there is not enough room for the pair, we need to start a new server even if it is not full
        serverlist.append(server)
        server={}
        serverid=serverid+1
        server[data['IP_A'][i]]=serverid
        server[data['IP_B'][i]]=serverid
        ips[data['IP_A'][i]]=1
        ips[data['IP_B'][i]]=1

In [59]:
#see what IPs are not in the ips dictionary that are in the unique ip array

for i in un_ips:
    if i not in ips:
        print(i)

In [28]:
len(ips) #yes we get the correct number of IPs, but why are we still getting duplicates??

351

Check that all IPs in the servers are unique

In [60]:
server_df=pd.DataFrame.from_records(serverlist)

In [61]:
server_df

,10003_106,10003_162,10003_235,10003_51,10011_132,10013_240,10021_188,10022_144,10022_207,10030_137,...,192.168.220.2,192.168.220.42,192.168.220.43,192.168.220.45,192.168.220.46,192.168.220.47,192.168.220.48,192.168.220.49,192.168.220.50,192.168.220.51
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,1
2,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,2
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.0,3.0,3.0,NaN,NaN,3.0,3
4,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4
5,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,NaN,NaN,NaN,5.0,5.0,5
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.0,NaN,6.0,NaN,6
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,7
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8.0,8.0,NaN,NaN,8.0,NaN,8.0,NaN,8
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,...,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,9.0,9
10,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,...,NaN,10.0,10.0,NaN,10.0,NaN,NaN,NaN,10.0,10
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11.0,11.0,NaN,11.0,11
12,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,12.0,NaN,NaN,12.0,12.0,NaN,12
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,13.0,NaN,NaN,13.0,13.0,13.0,NaN,NaN,13
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,14.0,NaN,14.0,NaN,14.0,NaN,NaN,14.0,14
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15.0,15.0,NaN,15
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,16.0,16.0,16.0,NaN,16.0,NaN,NaN,NaN,16
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,17.0,NaN,NaN,17.0,NaN,17.0,17.0,17
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,18.0,18.0,NaN,18.0,18.0,NaN,NaN,NaN,18
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,19.0,NaN,NaN,NaN,19.0,NaN,NaN,19.0,19
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20.0,NaN,20.0,20.0,NaN,NaN,20
21,NaN,NaN,NaN,21.0,NaN,NaN,NaN,NaN,NaN,21.0,...,NaN,21.0,21.0,NaN,NaN,NaN,NaN,NaN,NaN,21
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,22.0,NaN,NaN,22.0,22.0,22.0,NaN,22
23,NaN,NaN,NaN,NaN,NaN,23.0,NaN,NaN,NaN,NaN,...,23.0,NaN,23.0,23.0,23.0,23.0,NaN,NaN,NaN,23

In [62]:
server_df.count(axis=0) #we end up with duplicates... not sure why this is happening...

10003_106          1
10003_162          1
10003_235          1
10003_51           1
10011_132          1
10013_240          1
10021_188          1
10022_144          1
10022_207          1
10030_137          1
10030_147          1
10030_163          1
10030_164          1
10045_202          1
10045_94           1
10054_151          1
10057_27           1
10057_64           1
10058_130          1
10058_69           1
10067_13           1
10067_144          1
10072_35           1
10085_147          1
10088_156          1
10088_187          1
10088_191          1
10088_208          1
10088_216          1
10088_234          1
                  ..
14612_94           1
14620_188          1
192.168.100.1      1
192.168.100.14     1
192.168.100.2      1
192.168.100.20     1
192.168.200.1      1
192.168.210.45     6
192.168.210.46     1
192.168.210.47     6
192.168.210.48     4
192.168.210.49     3
192.168.210.50     2
192.168.210.52     2
192.168.210.53     7
192.168.210.54    10
192.168.210.55     5
192.168.210.56     9
192.168.210.57     5
192.168.220.1      1
192.168.220.2      1
192.168.220.42     9
192.168.220.43     9
192.168.220.45     7
192.168.220.46     5
192.168.220.47    17
192.168.220.48     8
192.168.220.49     7
192.168.220.50     9
192.168.220.51    24
Length: 339, dtype: int64

In [67]:
server_dft=server_df.transpose()
#filter out the duplicates by keeping the min server ID
server_dft['serverid']=server_dft.min(axis=1)

In [70]:
server_dft['IP']=server_dft.index

server_dft=server_dft[['IP', 'serverid']]

In [71]:
server_dft

                            IP  serverid
10003_106            10003_106      12.0
10003_162            10003_162       4.0
10003_235            10003_235       5.0
10003_51              10003_51      21.0
10011_132            10011_132       2.0
10013_240            10013_240      23.0
10021_188            10021_188      10.0
10022_144            10022_144       2.0
10022_207            10022_207       9.0
10030_137            10030_137      21.0
10030_147            10030_147      18.0
10030_163            10030_163      10.0
10030_164            10030_164       9.0
10045_202            10045_202       5.0
10045_94              10045_94      23.0
10054_151            10054_151       4.0
10057_27              10057_27      22.0
10057_64              10057_64      14.0
10058_130            10058_130      11.0
10058_69              10058_69       7.0
10067_13              10067_13      20.0
10067_144            10067_144      17.0
10072_35              10072_35      19.0
10085_147            10085_147       8.0
10088_156            10088_156      15.0
10088_187            10088_187      20.0
10088_191            10088_191      21.0
10088_208            10088_208       4.0
10088_216            10088_216      18.0
10088_234            10088_234       2.0
...                        ...       ...
14612_94              14612_94      15.0
14620_188            14620_188      15.0
192.168.100.1    192.168.100.1       0.0
192.168.100.14  192.168.100.14       0.0
192.168.100.2    192.168.100.2       0.0
192.168.100.20  192.168.100.20       2.0
192.168.200.1    192.168.200.1       4.0
192.168.210.45  192.168.210.45       5.0
192.168.210.46  192.168.210.46       6.0
192.168.210.47  192.168.210.47       4.0
192.168.210.48  192.168.210.48       6.0
192.168.210.49  192.168.210.49       1.0
192.168.210.50  192.168.210.50       4.0
192.168.210.52  192.168.210.52       1.0
192.168.210.53  192.168.210.53       0.0
192.168.210.54  192.168.210.54       0.0
192.168.210.55  192.168.210.55      12.0
192.168.210.56  192.168.210.56       0.0
192.168.210.57  192.168.210.57       4.0
192.168.220.1    192.168.220.1       0.0
192.168.220.2    192.168.220.2      23.0
192.168.220.42  192.168.220.42       4.0
192.168.220.43  192.168.220.43       1.0
192.168.220.45  192.168.220.45       3.0
192.168.220.46  192.168.220.46       3.0
192.168.220.47  192.168.220.47       0.0
192.168.220.48  192.168.220.48       1.0
192.168.220.49  192.168.220.49       5.0
192.168.220.50  192.168.220.50       3.0
192.168.220.51  192.168.220.51       0.0

[339 rows x 2 columns]

In [ ]:
#export these rules, and merge them into the dataset